### ISSUE TITLE
一次投票未结束，新建投票统计界面显示上轮投票

### ISSUE THREAD

**Issue by zhangzimo123** [hollykunge/Votes#224]
操作步骤：1.进入投票系统
                  2.点击新建投票 按要求填写信息 导入投票项
                  3.发起投票
                  4.再次新建投票 按要求填写信息 导入与上次投票不同的投票项
                  5.发起投票 点击统计
预期结果：统计界面投票项 显示正常
实际结果：统计界面投票项 显示上一轮投票项

**Comment by qiaocao** [comment]
已修正并提交
