### ISSUE TITLE
分数投票输入ee后提交出现undefined

### ISSUE THREAD

**Issue by zhangzimo123** [hollykunge/Votes#233]
操作步骤：1.发起分数投票
                   2.进入分数投票界面
                   3.任意候选人位置输入ee
                    4.错误提示出现后删除ee 再另一个候选人位置输入ee点击提交
预期结果：不能提交 提示输入正确数字
实际结果：可以提交第一行显示undefined

**Comment by yang49519845** [comment]
原因: 未判断输入格式是否未数字
已添加格式判断
